name: Actions command

on: 
  #push:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [jebuildmec]

  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run : |
          pwd
          ls -la
          echo "SHA: $GITHUB_SHA"
          echo "REPO : $GITHUB_REPOSITORY"
          echo "WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB token : ${{ github.token }}"

      - name: Check out
        uses: actions/checkout@v1
      
      - name: List files after checkout
        run : |
          pwd
          ls -la

      - name: JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Dan"

      - name : Log
        run: echo "${{ steps.greet.outputs.time }}"