name: Actions command

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Dan"
      - name : Log
        run: echo ${{
          steps.greet.outputs.time
         }}