name: Container
on: push

jobs:
  docker-step:
    runs-on: ubuntu-latest
    container:
      image: node:18-buster
    steps:
      - name : log node version
        run : |
          node -v
      - name : step with docker
        uses: docker://node:18-buster
        with:
          entrypoint: '/bin/echo'
          args: 'Cool la vie'
      
      - name:  step with docker suite
        uses: docker://node:18-buster
        with:
          entrypoint: /usr/local/bin/node
          args: -v

      - uses: actions/checkout@v1  
      - name: step with our own script
        uses: docker://node:18-buster
        with:
          entrypoint: ./script.sh
          args: "alors la"


  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
      # mais putain c un change
        image: mongo
        ports:
          - 27017:27017
    #container: 
    #  image:  node:18-buster
    #  options: --cpus 1
    steps:
      - name: Post a user
        run: |
          node -v
          echo "test from Magellan"
          cat /etc/os-release
          curl -X POST http://localhost:3001/api/users -H 'Content-Type: application/json' -d '{\"username\": \"hello\", \"address\": \"dwded\"}'