name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image:  node:18-buster
      options: --cpus 1
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release