name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-18.04
    steps:
      - name: Log node v6
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node v6 double check
        run: node -v