name: Matrix
on: push

jobs:
  node-version:
    runs-on: ${{ matrix.myos }}
    strategy:
      fail-fast: true
      matrix:
        mynode_version: [6, 7, 8]
        myos: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
          - myos: ubuntu-latest
            mynode_version: 6
          - myos: macos-latest
            mynode_version: 6
          - myos: macos-latest
            mynode_version: 7
          - myos: windows-latest
            
      #max-parallel: 2
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.mynode_version }} 
      - name: Log node version double check
        run: node -v