name: Simple shell commands

on: [push]

jobs:
  run-windows-command:
    runs-on: windows-2019
    steps:
      - run: Get-Location
      - run: pwd
        shell: bash

  run-shell-command:
    needs:  ['run-windows-command']
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "La classe les gars"
        continue-on-error: true
      - name: echo another string
        run: | 
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print("ah ouais meme en python !" + platform.processor())
        shell: python